### ISSUE TITLE
表情包云控

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/DanXi-Backend#5]

**Comment by KYLN24** [comment]
@w568w @fsy2001
ref:
- https://github.com/DanXi-Dev/DanXi/issues/446
- https://github.com/DanXi-Dev/DanXi-swift/issues/336

**Comment by KYLN24** [comment]
propose 一个格式，大家看看行不行：

```toml
[[stickers]]
id = "dx_call"
url = "https://..."
description = "需要这个字段吗？"
updated = 1979-05-27T07:32:00Z
```

需要讨论的点：
1. 是否需要 `description` 字段？
2. updated 时间需要确认具体格式，请参考
  - [Offset Date-Time](https://toml.io/en/v1.0.0#offset-date-time)
  - [Local Date-Time](https://toml.io/en/v1.0.0#local-date-time)

@w568w @fsy2001
